[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.devopspractice08.online

[redis]
redis-dev.devopspractice08.online

[user]
user-dev.devopspractice08.online

[cart]
cart-dev.devopspractice08.online

[mysql]
mysql-dev.devopspractice08.online

[shipping]
shipping-dev.devopspractice08.online

[rabbitmq]
rabbitmq-dev.devopspractice08.online

[payment]
payment-dev.devopspractice08.online

[frontend]
frontend-dev.devopspractice08.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MYSQL_ROOT_PASSWORD=Roboshop@1
