- name: task-1
  ansible.builtin.debug:
    msg: "Hi, from Task-1"

- name: set facts
  ansible.builtin.set_fact:
    os: "debian"

- name: task-2
  ansible.builtin.debug:
    msg: "Hi, from Task-2"

- name: task-3
  ansible.builtin.debug:
    msg: "Hi, from Task-3"